### ISSUE TITLE
Create Jammy VMs

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/abid#130]
Hosts to be created and provisioned:

**Host Names**

Staging (done): `abid-staging1` (turned off), `abid-staging2` (in use)
Production (needed): `abid-prod1`, `abid-prod2`

**Reasoning**

They're on Focal machines now and are falling apart.

Used for https://github.com/pulibrary/princeton_ansible/pull/4031 

# Deadline

I don't have a deadline. This application is important, but isn't used by many people, and is an internal tool. Upgrading these is to prevent us from all having to respond to another incident report about it being down.

**Comment by hackartisan** [comment]
current abid machines: https://github.com/pulibrary/princeton_ansible/blob/1e26ff51514d71323d836915ea609778e459dd25/inventory/all_projects/abid

**Comment by acozine** [comment]
Two new jammy boxes are ready: abid-prod1 and abid-prod2. They have had all their packages and their kernels updated. The playbooks should do the rest, though they need to be added to inventory. I'll leave this open for now in case there's something I've forgotten, but I think we are good to go.

**Comment by hackartisan** [comment]
Ansible ran fine, application is deployed. Thank you!
