### ISSUE TITLE
Alma Timeouts Should Re-Render Batch Form

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/abid#163]
https://app.honeybadger.io/projects/87494/faults/108018126

## Description

When Alma times out our users lose all their work entering barcodes in the marc_batch form. The form should re-render with the barcodes still entered and tell them to try again.

## Acceptance Criteria

- [x] Timeout should be increased
- [ ] Form should re-render if the Alma call errors.

## Sudden Priority Justification

Michael Siravo's having a hard time getting his work done, and is having to redo work.

## First Step

Find the feature spec for marc batches and stub out the Alma lookup so it fails.

**Comment by eliotjordan** [comment]
- Added a larger Alma timeout, which should hopefully help with this. 
- Did not implement the form re-render, as working locally on this app is difficult, and may not be neccessary.
- Slack messaged Michael Siravo and asked him to let us know if he is still encountering issues. 
- If he is not, then we may be able to close this ticket.

**Comment by tpendragon** [comment]
Pinged Michael, if he says it's better I'll close this.
