### ISSUE TITLE
Batches should return a CSV of its properties as a report.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/abid#6]

**Comment by eliotjordan** [comment]
Are we looking for a report that lists:

1. Properties of the batch itself (start_box, end_box, first_barcode, etc.)
1. Properties of the related absolute_identifier? (full_identifier, barcode, etc.)
2. Both?
3. Something else?

**Comment by tpendragon** [comment]
[1.csv](https://github.com/pulibrary/abid/files/6601216/1.csv)

This is what it looks like on lib-jobs.

**Comment by eliotjordan** [comment]
So that looks like option 2. Barcodes and AbIDs etc.
