### ISSUE TITLE
locations drop-down fails to populate with updated location codes

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/abid#92]
When we change the current location codes in ArchivesSpace to the new non-requestable location codes, the locations drop-down in AbID fails to pull them in. 

What happens instead is that the old one disappears. Will is going to add screenshots below to demonstrate.

Based on https://github.com/pulibrary/abid/blob/2c98804bf9103115009cb7c5044a2c410c0bc411/app/models/batch.rb#L51 we had assumed they would dynamically update; we now suspect a caching issue, or perhaps there is a hardcoded string-check or config somewhere that needs to be updated.

Sorry this is dropping out of the blue--it's a somewhat urgent request. Thank you!!

## Sudden Priority Justification

This is blocking a scheduled data migration for archivespace location values.

**Comment by Will-Clements** [comment]
![Screenshot (26)](https://user-images.githubusercontent.com/60931023/201371925-7eeac129-e796-47df-81cd-504937d7d729.png)
note that MSS Vault is missing, after I changed the code in ASpace from "mss" to "scamss"

**Comment by regineheberlein** [comment]
@hackartisan kicked the app for us, but it made no difference. The same error is also happening in abid-staging.
